# Run locally with nginx reverse proxy
# sudo docker compose -f docker-compose.app.yml -f docker-compose.local.yml up -d

services:
  nginx:
    image: nginx:alpine
    container_name: menuwire-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./media:/app/media:ro
      - backend_static:/app/static:ro
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
