services:
  backend:
    build: ./backend
    container_name: menuwire-backend
    env_file:
      - ./.env
    volumes:
      - ./backend/media:/app/media
      - backend_static:/app/static
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: menuwire-frontend
    env_file:
      - ./.env
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: menuwire-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/media:/app/media
      - backend_static:/app/static
    restart: unless-stopped

volumes:
  backend_static: